services:
  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    secrets:
      - postgres_password

  backend:
    build: .
    container_name: backend
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_SERVER=postgres
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
    secrets:
      - postgres_password
    command: ./start.sh uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt